spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:odin-driver.yaml
      - optional:nacos:register.yaml
      - optional:nacos:odin-weixin.yaml
      - optional:nacos:sentinel.yaml
      - optional:nacos:oss.yaml
      - optional:nacos:mybatis.yaml
      - optional:nacos:redis.yaml
