spring:
  application:
    name: odin-user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/odin_shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      minimum-idle: 5
      auto-commit: true
      idle-timeout: 600000
      maximum-pool-size: 20
      pool-name: OdinHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    redis:
      host: 127.0.0.1
      password: 123456

server:
  port: 9001
