spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  config:
    import:
      - optional:nacos:odin-order.yaml
      - optional:nacos:register.yaml
      - optional:nacos:sentinel.yaml
      - optional:nacos:mybatis.yaml
      - optional:nacos:redis.yaml
